/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-06-15 19:55:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import clothes.utils.Constants;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/Users/Vo%20Quang%20Tuong/WebBanHang_backup_te-them_admin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanQuanAo/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/views/include/footer.jsp", Long.valueOf(1653491080168L));
    _jspx_dependants.put("jar:file:/C:/Users/Vo%20Quang%20Tuong/WebBanHang_backup_te-them_admin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanQuanAo/WEB-INF/lib/jstl-impl.jar!/META-INF/fmt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1653158204728L));
    _jspx_dependants.put("jar:file:/C:/Users/Vo%20Quang%20Tuong/WebBanHang_backup_te-them_admin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanQuanAo/WEB-INF/lib/jstl-impl.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/C:/Users/Vo%20Quang%20Tuong/WebBanHang_backup_te-them_admin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanQuanAo/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1653676131777L));
    _jspx_dependants.put("jar:file:/C:/Users/Vo%20Quang%20Tuong/WebBanHang_backup_te-them_admin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebBanQuanAo/WEB-INF/lib/jstl-impl.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1653158204605L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("clothes.utils.Constants");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("	href=\"/resources/images/icons/favicon.ico\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset='utf-8'>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<header class=\"header trans_300\">\r\n");
      out.write("	<div class=\"main_nav_container\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12 text-right\">\r\n");
      out.write("					<div class=\"logo_container\">\r\n");
      out.write("						<a href=\"#\">YAME <span>shop</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<nav class=\"navbar\">\r\n");
      out.write("						<ul class=\"navbar_menu\">\r\n");
      out.write("							<li><a href=\"home.htm\"><button type=\"button\"\r\n");
      out.write("									class=\"btn btn-success position-relative\">Trang chủ</button></a></li>\r\n");
      out.write("							<li><a href=\"category/index.htm\"><button type=\"button\"\r\n");
      out.write("									class=\"btn btn-success position-relative\">Mua sắm</button></a></li>\r\n");
      out.write("							<li>");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("							<i class=\"bi bi-cart-check-fill\"></i>\r\n");
      out.write("						</ul>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"hamburger_container\">\r\n");
      out.write("							<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.0/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.2.1/hamburgers.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Đăng Nhập</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" body { }\r\n");
      out.write(".footer-widget p {\r\n");
      out.write("    margin-bottom: 27px;\r\n");
      out.write("}\r\n");
      out.write("p1 {\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("  color:white;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("}\r\n");
      out.write(" .animate-border {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 115px;\r\n");
      out.write("  height: 3px;\r\n");
      out.write("  background: #007bff; }\r\n");
      out.write("\r\n");
      out.write(".animate-border:after {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  width: 35px;\r\n");
      out.write("  height: 3px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  border-left: 10px solid #fff;\r\n");
      out.write("  border-right: 10px solid #fff;\r\n");
      out.write("  -webkit-animation: animborder 2s linear infinite;\r\n");
      out.write("  animation: animborder 2s linear infinite; }\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes animborder {\r\n");
      out.write("  0% {\r\n");
      out.write("    -webkit-transform: translateX(0px);\r\n");
      out.write("    transform: translateX(0px); }\r\n");
      out.write("  100% {\r\n");
      out.write("    -webkit-transform: translateX(113px);\r\n");
      out.write("    transform: translateX(113px); } }\r\n");
      out.write("\r\n");
      out.write("@keyframes animborder {\r\n");
      out.write("  0% {\r\n");
      out.write("    -webkit-transform: translateX(0px);\r\n");
      out.write("    transform: translateX(0px); }\r\n");
      out.write("  100% {\r\n");
      out.write("    -webkit-transform: translateX(113px);\r\n");
      out.write("    transform: translateX(113px); } }\r\n");
      out.write("\r\n");
      out.write(".animate-border.border-white:after {\r\n");
      out.write("  border-color: #fff; }\r\n");
      out.write("\r\n");
      out.write(".animate-border.border-yellow:after {\r\n");
      out.write("  border-color: #F5B02E; }\r\n");
      out.write("\r\n");
      out.write(".animate-border.border-orange:after {\r\n");
      out.write("  border-right-color: #007bff;\r\n");
      out.write("  border-left-color: #007bff; }\r\n");
      out.write("\r\n");
      out.write(".animate-border.border-ash:after {\r\n");
      out.write("  border-right-color: #EEF0EF;\r\n");
      out.write("  border-left-color: #EEF0EF; }\r\n");
      out.write("\r\n");
      out.write(".animate-border.border-offwhite:after {\r\n");
      out.write("  border-right-color: #F7F9F8;\r\n");
      out.write("  border-left-color: #F7F9F8; }\r\n");
      out.write("\r\n");
      out.write("/* Animated heading border */\r\n");
      out.write("@keyframes primary-short {\r\n");
      out.write("  0% {\r\n");
      out.write("    width: 15%; }\r\n");
      out.write("  50% {\r\n");
      out.write("    width: 90%; }\r\n");
      out.write("  100% {\r\n");
      out.write("    width: 10%; } }\r\n");
      out.write("\r\n");
      out.write("@keyframes primary-long {\r\n");
      out.write("  0% {\r\n");
      out.write("    width: 80%; }\r\n");
      out.write("  50% {\r\n");
      out.write("    width: 0%; }\r\n");
      out.write("  100% {\r\n");
      out.write("    width: 80%; } } \r\n");
      out.write("\r\n");
      out.write(".dk-footer {\r\n");
      out.write("  padding: 75px 0 0;\r\n");
      out.write("  background-color: #151414;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  z-index: 2; }\r\n");
      out.write("  .dk-footer .contact-us {\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("    padding-left: 80px; }\r\n");
      out.write("    .dk-footer .contact-us .contact-info {\r\n");
      out.write("      margin-left: 50px; }\r\n");
      out.write("    .dk-footer .contact-us.contact-us-last {\r\n");
      out.write("      margin-left: -80px; }\r\n");
      out.write("  .dk-footer .contact-icon i {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    top: -15px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    color:#007bff; }\r\n");
      out.write("\r\n");
      out.write(".dk-footer-box-info {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: -122px;\r\n");
      out.write("  background: #202020;\r\n");
      out.write("  padding: 40px;\r\n");
      out.write("  z-index: 2; }\r\n");
      out.write("  .dk-footer-box-info .footer-social-link h3 {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    margin-bottom: 25px; }\r\n");
      out.write("  .dk-footer-box-info .footer-social-link ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0; }\r\n");
      out.write("  .dk-footer-box-info .footer-social-link li {\r\n");
      out.write("    display: inline-block; }\r\n");
      out.write("  .dk-footer-box-info .footer-social-link a i {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 40px;\r\n");
      out.write("    background: #000;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("    color: #fff; }\r\n");
      out.write("    .dk-footer-box-info .footer-social-link a i.fa-facebook {\r\n");
      out.write("      background-color: #3B5998; }\r\n");
      out.write("    .dk-footer-box-info .footer-social-link a i.fa-twitter {\r\n");
      out.write("      background-color: #55ACEE; }\r\n");
      out.write("    .dk-footer-box-info .footer-social-link a i.fa-google-plus {\r\n");
      out.write("      background-color: #DD4B39; }\r\n");
      out.write("    .dk-footer-box-info .footer-social-link a i.fa-linkedin {\r\n");
      out.write("      background-color: #0976B4; }\r\n");
      out.write("    .dk-footer-box-info .footer-social-link a i.fa-instagram {\r\n");
      out.write("      background-color: #B7242A; }\r\n");
      out.write("\r\n");
      out.write(".footer-awarad {\r\n");
      out.write("  margin-top: 285px;\r\n");
      out.write("  display: -webkit-box;\r\n");
      out.write("  display: -webkit-flex;\r\n");
      out.write("  display: -moz-box;\r\n");
      out.write("  display: -ms-flexbox;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  -webkit-box-flex: 0;\r\n");
      out.write("  -webkit-flex: 0 0 100%;\r\n");
      out.write("  -moz-box-flex: 0;\r\n");
      out.write("  -ms-flex: 0 0 100%;\r\n");
      out.write("  flex: 0 0 100%;\r\n");
      out.write("  -webkit-box-align: center;\r\n");
      out.write("  -webkit-align-items: center;\r\n");
      out.write("  -moz-box-align: center;\r\n");
      out.write("  -ms-flex-align: center;\r\n");
      out.write("  align-items: center; }\r\n");
      out.write("  .footer-awarad p {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("    padding-top: 15px; }\r\n");
      out.write("\r\n");
      out.write(".footer-info-text {\r\n");
      out.write("  margin: 26px 0 32px; }\r\n");
      out.write("\r\n");
      out.write(".footer-left-widget {\r\n");
      out.write("  padding-left: 80px; }\r\n");
      out.write("\r\n");
      out.write(".footer-widget .section-heading {\r\n");
      out.write("  margin-bottom: 35px; }\r\n");
      out.write("\r\n");
      out.write(".footer-widget h3 {\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("  max-width: -webkit-fit-content;\r\n");
      out.write("  max-width: -moz-fit-content;\r\n");
      out.write("  max-width: fit-content; }\r\n");
      out.write("\r\n");
      out.write(".footer-widget ul {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  float: left;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0; }\r\n");
      out.write("\r\n");
      out.write(".footer-widget li {\r\n");
      out.write("  margin-bottom: 18px; }\r\n");
      out.write("\r\n");
      out.write(".footer-widget p {\r\n");
      out.write("  margin-bottom: 27px; }\r\n");
      out.write("\r\n");
      out.write(".footer-widget a {\r\n");
      out.write("  color: #878787;\r\n");
      out.write("  -webkit-transition: all 0.3s;\r\n");
      out.write("  -o-transition: all 0.3s;\r\n");
      out.write("  transition: all 0.3s; }\r\n");
      out.write("  .footer-widget a:hover {\r\n");
      out.write("    color: #007bff; }\r\n");
      out.write("\r\n");
      out.write(".footer-widget:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: block;\r\n");
      out.write("  clear: both; }\r\n");
      out.write("\r\n");
      out.write(".dk-footer-form {\r\n");
      out.write("  position: relative; }\r\n");
      out.write("  .dk-footer-form input[type=email] {\r\n");
      out.write("    padding: 14px 28px;\r\n");
      out.write("    border-radius: 50px;\r\n");
      out.write("    background: #2E2E2E;\r\n");
      out.write("    border: 1px solid #2E2E2E; }\r\n");
      out.write("  .dk-footer-form input::-webkit-input-placeholder, .dk-footer-form input::-moz-placeholder, .dk-footer-form input:-ms-input-placeholder, .dk-footer-form input::-ms-input-placeholder, .dk-footer-form input::-webkit-input-placeholder {\r\n");
      out.write("    color: #878787;\r\n");
      out.write("    font-size: 14px; }\r\n");
      out.write("  .dk-footer-form input::-webkit-input-placeholder, .dk-footer-form input::-moz-placeholder, .dk-footer-form input:-ms-input-placeholder, .dk-footer-form input::-ms-input-placeholder, .dk-footer-form input::placeholder {\r\n");
      out.write("    color: #878787;\r\n");
      out.write("    font-size: 14px; }\r\n");
      out.write("  .dk-footer-form button[type=submit] {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    padding: 12px 24px 12px 17px;\r\n");
      out.write("    border-top-right-radius: 25px;\r\n");
      out.write("    border-bottom-right-radius: 25px;\r\n");
      out.write("    border: 1px solid #007bff;\r\n");
      out.write("    background: #007bff;\r\n");
      out.write("    color: #fff; }\r\n");
      out.write("  .dk-footer-form button:hover {\r\n");
      out.write("    cursor: pointer; }\r\n");
      out.write("\r\n");
      out.write("/* ==========================\r\n");
      out.write("\r\n");
      out.write("    Contact\r\n");
      out.write("\r\n");
      out.write("=============================*/\r\n");
      out.write(".contact-us {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  z-index: 2;\r\n");
      out.write("  margin-top: 65px;\r\n");
      out.write("  display: -webkit-box;\r\n");
      out.write("  display: -webkit-flex;\r\n");
      out.write("  display: -moz-box;\r\n");
      out.write("  display: -ms-flexbox;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  -webkit-box-align: center;\r\n");
      out.write("  -webkit-align-items: center;\r\n");
      out.write("  -moz-box-align: center;\r\n");
      out.write("  -ms-flex-align: center;\r\n");
      out.write("  align-items: center; }\r\n");
      out.write("\r\n");
      out.write(".contact-icon {\r\n");
      out.write("  position: absolute; }\r\n");
      out.write("  .contact-icon i {\r\n");
      out.write("    font-size: 36px;\r\n");
      out.write("    top: -5px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    color: #007bff; }\r\n");
      out.write("\r\n");
      out.write(".contact-info {\r\n");
      out.write("  margin-left: 75px;\r\n");
      out.write("  color: #fff; }\r\n");
      out.write("  .contact-info h3 {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin-bottom: 0; }\r\n");
      out.write("\r\n");
      out.write(".copyright {\r\n");
      out.write("  padding: 28px 0;\r\n");
      out.write("  margin-top: 55px;\r\n");
      out.write("  background-color: #202020; }\r\n");
      out.write("  .copyright span,\r\n");
      out.write("  .copyright a {\r\n");
      out.write("    color: #878787;\r\n");
      out.write("    -webkit-transition: all 0.3s linear;\r\n");
      out.write("    -o-transition: all 0.3s linear;\r\n");
      out.write("    transition: all 0.3s linear; }\r\n");
      out.write("  .copyright a:hover {\r\n");
      out.write("    color:#007bff; }\r\n");
      out.write("\r\n");
      out.write(".copyright-menu ul {\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  margin: 0; }\r\n");
      out.write("\r\n");
      out.write(".copyright-menu li {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding-left: 20px; }\r\n");
      out.write("\r\n");
      out.write(".back-to-top {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  z-index: 2; }\r\n");
      out.write("  .back-to-top .btn-dark {\r\n");
      out.write("    width: 35px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    bottom: 20px;\r\n");
      out.write("    right: 20px;\r\n");
      out.write("    background: #2e2e2e;\r\n");
      out.write("    border-color: #2e2e2e;\r\n");
      out.write("    display: none;\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("    -webkit-transition: all 0.3s linear;\r\n");
      out.write("    -o-transition: all 0.3s linear;\r\n");
      out.write("    transition: all 0.3s linear; }\r\n");
      out.write("    .back-to-top .btn-dark:hover {\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      background: #FA6742;\r\n");
      out.write("      border-color: #FA6742; }\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\r\n");
      out.write("<footer id=\"dk-footer\" class=\"dk-footer\">              \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12 col-lg-4\">\r\n");
      out.write("                    <div class=\"dk-footer-box-info\">\r\n");
      out.write("                        <a href=\"index.html\" class=\"footer-logo\">\r\n");
      out.write("                            <img src=\"https://cdn.pixabay.com/photo/2016/11/07/13/04/yoga-1805784_960_720.png\" alt=\"footer_logo\" class=\"img-fluid\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <p1 class=\"footer-info-text\">\r\n");
      out.write("                           Đồ án môn Lập Trình Web \r\n");
      out.write("                        </p1>\r\n");
      out.write("                        <br><br><br>\r\n");
      out.write("                        <div class=\"footer-social-link\">\r\n");
      out.write("                            Giảng viên hướng dẫn\r\n");
      out.write("                            <div class=\"p-3 mb-2 bg-info text-white text-center\">NGUYỄN TRUNG HIẾU</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- End Social link -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End Footer info -->\r\n");
      out.write("                    <div class=\"footer-awarad\">\r\n");
      out.write("                        <img src=\"images/icon/best.png\" alt=\"\">\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Col -->\r\n");
      out.write("                <div class=\"col-md-12 col-lg-8\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"contact-us\">\r\n");
      out.write("                                <div class=\"contact-icon\">\r\n");
      out.write("                                    <i class=\"fa fa-map-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- End contact Icon -->\r\n");
      out.write("                                <div class=\"contact-info\">\r\n");
      out.write("                                    <h3>Địa chỉ:</h3>\r\n");
      out.write("                                    <p1>97 Man Thiện, Hiệp Phú</p1>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- End Contact Info -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End Contact Us -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- End Col -->\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"contact-us contact-us-last\">\r\n");
      out.write("                                <div class=\"contact-icon\">\r\n");
      out.write("                                    <i class=\"fa fa-volume-control-phone\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- End contact Icon -->\r\n");
      out.write("                                <div class=\"contact-info\">\r\n");
      out.write("                                    <h3>0339518617</h3>\r\n");
      out.write("                                    <p1>Hãy liên hệ với chúng tôi</p1>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <!-- End Contact Info -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End Contact Us -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- End Col -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                  \r\n");
      out.write("                    <!-- End Contact Row -->\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12 col-lg-6\">\r\n");
      out.write("                            <div class=\"footer-widget footer-left-widget\">\r\n");
      out.write("                                <div class=\"section-heading\">                                 \r\n");
      out.write("                                    <span class=\"animate-border border-black\"></span>\r\n");
      out.write("                                </div>                                                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End Footer Widget -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- End col -->\r\n");
      out.write("                            <div class=\"footer-widget\">\r\n");
      out.write("                                <div class=\"section-heading\">\r\n");
      out.write("                                    <span class=\"animate-border border-black\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"p-3 mb-2 bg-success text-white text-center \">VÕ QUANG TƯỜNG - N19DCCN185</div>\r\n");
      out.write("                                 <div class=\"p-3 mb-2 bg-success text-white text-center\">LÊ HOÀNG ANH - N19DCCN005</div>\r\n");
      out.write("                                  <div class=\"p-3 mb-2 bg-success text-white text-center\">THẨM NGỌC ÁNH - N19DCCN012</div>\r\n");
      out.write("                                <!-- End form -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        <!-- End Col -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End Row -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Col -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Row -->\r\n");
      out.write("        </div>     \r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      if (_jspx_meth_c_005furl_005f12(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.7.2/vanilla-tilt.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/account/signin.jsp(15,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/account/signin.jsp(18,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/login/css/util.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/account/signin.jsp(20,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/login/css/style.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/include/header.jsp(35,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<a href=\"cart/index.htm\"><button type=\"button\"\r\n");
          out.write("											class=\"btn btn-success position-relative\">\r\n");
          out.write("											Giỏ hàng <span\r\n");
          out.write("												class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger\">\r\n");
          out.write("												");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.carts.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </span>\r\n");
          out.write("										</button></a>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/include/header.jsp(46,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div class=\"nav-item dropdown\">\r\n");
          out.write("									<a href=\"\" data-toggle=\"dropdown\"\r\n");
          out.write("										class=\"nav-link dropdown-toggle user-action\"><img\r\n");
          out.write("										src=\"");
          if (_jspx_meth_c_005furl_005f3(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\" alt=\"\"\r\n");
          out.write("										class=\"avatar\" alt=\"Avatar\"> Tài Khoản <b class=\"caret\">\r\n");
          out.write("									</b></a>\r\n");
          out.write("									<div class=\"dropdown-menu\">\r\n");
          out.write("										<a href=\"account/signin.htm\" class=\"dropdown-item\"><i\r\n");
          out.write("											class=\"fa fa-user-o\"></i> Đăng nhập</a> <a\r\n");
          out.write("											href=\"account/register.htm\" class=\"dropdown-item\"><i\r\n");
          out.write("											class=\"fa fa-calendar-o\"></i> Đăng ký</a>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/views/include/header.jsp(50,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/images/3.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div class=\"nav-item dropdown\">\r\n");
          out.write("									");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									<div class=\"dropdown-menu\">\r\n");
          out.write("										<a href=\"order/index.htm\" class=\"dropdown-item\"><i\r\n");
          out.write("											class=\"fa fa-user-o\"></i> Đơn hàng của tôi</a>\r\n");
          out.write("										");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("										<a href=\"account/profile.htm\" class=\"dropdown-item\"><i\r\n");
          out.write("											class=\"fa fa-user-o\"></i> Trang cá nhân</a> <a\r\n");
          out.write("											href=\"./account/change.htm\" class=\"dropdown-item\"><i\r\n");
          out.write("											class=\"fa fa-user-o\"></i> Đổi mật khẩu</a>\r\n");
          out.write("										<div class=\"dropdown-divider\"></div>\r\n");
          out.write("										<a href=\"account/logout.htm\" class=\"dropdown-item\"><i\r\n");
          out.write("											class=\"material-icons\">&#xE8AC;</i> Logout</a>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("										");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/include/header.jsp(65,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account.type == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<a href=\"#\" data-toggle=\"dropdown\"\r\n");
          out.write("												class=\"nav-link dropdown-toggle user-action\"><img\r\n");
          out.write("												src=\"");
          if (_jspx_meth_c_005furl_005f4(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write("\" alt=\"\"\r\n");
          out.write("												class=\"avatar\" alt=\"Avatar\">\r\n");
          out.write("												");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account.fullname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("(admin) <b class=\"caret\">\r\n");
          out.write("											</b></a>\r\n");
          out.write("											<br />\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      // /WEB-INF/views/include/header.jsp(68,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/resources/images/3.jpg");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("											<a href=\"#\" data-toggle=\"dropdown\"\r\n");
          out.write("												class=\"nav-link dropdown-toggle user-action\"><img\r\n");
          out.write("												src=\"");
          if (_jspx_meth_c_005furl_005f5(_jspx_th_c_005fotherwise_005f1, _jspx_page_context))
            return true;
          out.write("\" alt=\"\"\r\n");
          out.write("												class=\"avatar\" alt=\"Avatar\">\r\n");
          out.write("												");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account.fullname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" <b class=\"caret\"> </b></a>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f1);
      // /WEB-INF/views/include/header.jsp(78,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/resources/images/3.jpg");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/include/header.jsp(86,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account.type == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<a href=\"admin.htm\" class=\"dropdown-item\"><i\r\n");
          out.write("												class=\"fa fa-sliders\"></i> Quản trị admin</a>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/account/signin.jsp(40,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/resources/plugins/font-awesome-4.7.0/css/font-awesome.min.css");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/account/signin.jsp(43,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/resources/plugins/OwlCarousel2-2.2.1/animate.css");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/account/signin.jsp(45,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/resources/styles/main_styles.css");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/account/signin.jsp(47,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/resources/styles/responsive.css");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/views/account/signin.jsp(56,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("account/signin.htm");
      // /WEB-INF/views/account/signin.jsp(56,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/views/account/signin.jsp(56,1) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setModelAttribute("user");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		<div class=\"limiter\">\r\n");
            out.write("			<div class=\"container-login100\">\r\n");
            out.write("				<div class=\"login100-pic js-tilt\" data-tilt data-tilt-max=\"20\"\r\n");
            out.write("					data-tilt-speed=\"100\" data-tilt-perspective=\"500\">\r\n");
            out.write("					<img src=\"");
            if (_jspx_meth_c_005furl_005f10(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\"\r\n");
            out.write("						alt=\"IMG\">\r\n");
            out.write("				</div>\r\n");
            out.write("				<div class=\"wrap-login100\">\r\n");
            out.write("					<form class=\"login100-form validate-form\">\r\n");
            out.write("						<span class=\"login100-form-title\"> Đăng nhập </span>\r\n");
            out.write("						<div class=\"forgot-header\">\r\n");
            out.write("							<h6 style=\"color: red; font-style: italic; padding-top: 15px;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("						</div>\r\n");
            out.write("						<div class=\"wrap-input100 validate-input\"\r\n");
            out.write("							data-validate=\"Valid email is required: ex@abc.xyz\">\r\n");
            out.write("							<input class=\"input100\" type=\"text\" name=\"email\"\r\n");
            out.write("								placeholder=\"Email\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /> <span\r\n");
            out.write("								class=\"focus-input100\"></span> <span class=\"symbol-input100\">\r\n");
            out.write("								<i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\r\n");
            out.write("							</span>\r\n");
            out.write("						</div>\r\n");
            out.write("\r\n");
            out.write("						<div class=\"wrap-input100 validate-input\"\r\n");
            out.write("							data-validate=\"Password is required\">\r\n");
            out.write("							<input class=\"input100\" type=\"password\" name=\"pw\"\r\n");
            out.write("								placeholder=\"Password\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /> <span\r\n");
            out.write("								class=\"focus-input100\"></span> <span class=\"symbol-input100\">\r\n");
            out.write("								<i class=\"fa fa-lock\" aria-hidden=\"true\"></i>\r\n");
            out.write("							</span>\r\n");
            out.write("						</div>\r\n");
            out.write("						<span style=\"color: #001100; font-style: italic;\"> <input\r\n");
            out.write("							type=\"checkbox\" name=\"rm\" /> Nhớ tài khoản\r\n");
            out.write("						</span>\r\n");
            out.write("						<div class=\"container-login100-form-btn\">\r\n");
            out.write("							<button type=\"submit\" class=\"login100-form-btn\">Đăng\r\n");
            out.write("								nhập</button>\r\n");
            out.write("						</div>\r\n");
            out.write("\r\n");
            out.write("						<div class=\"text-center p-t-12\">\r\n");
            out.write("							<span class=\"txt1\"> Bạn quên </span> <a class=\"txt2\"\r\n");
            out.write("								href=\"account/forgot.htm\">Email/ Mật khẩu? </a>\r\n");
            out.write("						</div>\r\n");
            out.write("\r\n");
            out.write("						<div class=\"text-center p-t-12\">\r\n");
            out.write("							<a class=\"txt2\" href=\"account/register.htm\"> Chưa có tài\r\n");
            out.write("								khoản thì tạo ngay nào <i class=\"fa fa-long-arrow-right m-l-5\"\r\n");
            out.write("								aria-hidden=\"true\"></i>\r\n");
            out.write("							</a>\r\n");
            out.write("						</div>\r\n");
            out.write("					</form>\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("		</div>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/account/signin.jsp(62,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/resources/login/images/img-01.png");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /WEB-INF/views/account/signin.jsp(118,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/resources/styles/bootstrap4/popper.js");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent(null);
      // /WEB-INF/views/account/signin.jsp(124,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/resources/login/js/main.js");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }
}
